version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip3 install black flake8 isort
      # isort isn't compatible with black yet:
      # https://github.com/timothycrosley/isort/issues/694
      # https://github.com/python/black/issues/333
      # - run: isort --check -rc .
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:3
    steps:
      - run: pip3 install pytest pytest-cov
      - checkout
      - run: pip3 install .[all]
      # The tests
      - run:
          command: pytest --cov pyfoobar
          working_directory: test/
          env:
            MPLBACKEND: Agg
      # submit to codecov
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
